---
- name: Create project directory structure
  tags: [deploy]
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ sentinel_path }}/agent"
    - "{{ sentinel_path }}/config"
    - "{{ web_root }}"
    - "{{ web_root }}/{{ sentinel_prefix }}"

- name: Upload Agent source code
  tags: [deploy]
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../agent/"
    dest: "{{ sentinel_path }}/agent/"
    mode: "0644"
  notify: Restart bot

- name: Sync configuration TOML files (Except hugo.toml)
  tags: [deploy, secrets]
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../config/{{ item }}"
    dest: "{{ sentinel_path }}/config/{{ item }}"
    mode: "0644"
  loop:
    - "watch_list.toml"
    - "settings.toml"
  notify: Restart bot
