---
- name: Upload Agent source code
  tags: [deploy]
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../agent/"
    dest: "{{ app_user_home }}/agent/"
    mode: "0644"
    owner: "{{ app_user_name }}"
    group: "{{ app_user_name }}"
  notify: Restart bot

- name: Sync configuration TOML files (Except hugo.toml)
  tags: [deploy, secrets]
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../config/{{ item }}"
    dest: "{{ app_user_home }}/config/{{ item }}"
    mode: "0644"
    owner: "{{ app_user_name }}"
    group: "{{ app_user_name }}"
  loop:
    - "watch_list.toml"
    - "settings.toml"
  notify: Restart bot
