---
- name: Create Hugo application directory
  tags: [hugo, deploy]
  ansible.builtin.file:
    path: "{{ app_user_home }}/hugo"
    state: directory
    owner: "{{ app_user_name }}"
    group: "{{ app_user_name }}"
    mode: "0755"
  become: true

- name: Create Hugo content and layout subdirectories
  tags: [hugo, deploy]
  ansible.builtin.file:
    path: "{{ app_user_home }}/hugo/{{ item }}"
    state: directory
    owner: "{{ app_user_name }}"
    group: "{{ app_user_name }}"
    mode: "0755"
  loop:
    - content/news/archives
    - content/reports/archives
    - layouts/_default
    - static/css
  become: true
  become_user: "{{ app_user_name }}"

- name: Create Hugo webroot directory
  tags: [hugo, deploy]
  ansible.builtin.file:
    path: "{{ web_base }}/{{ domain }}{% if sentinel_prefix %}/{{ sentinel_prefix }}{% endif %}"
    state: directory
    owner: "{{ app_user_name }}"
    group: "{{ app_user_name }}"
    mode: "0755"
  become: true
